version: '2'
services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - C:/workspace/projects/fiap/monitoramento/mongodb:/data/db
  monitoramento:
    container_name: monitoramento
    build: .
    restart: always
    image: monitoramento:latest
    ports:
      - "8080:8080"
    depends_on:
      - mongo